base/urls.py
"""
Nombre del software: SIGETP

Descripción: Sistema Integrado de Información y Documentación Geoestadística y Tecnopolítica

Nombre del licenciante y año: Fundación CIDA (2017)

Autores: William Páez

La Fundación Centro Nacional de Desarrollo e Investigación en Tecnologías Libres (CENDITEL),
ente adscrito al Ministerio del Poder Popular para Educación Universitaria, Ciencia y Tecnología
(MPPEUCT), concede permiso para usar, copiar, modificar y distribuir libremente y sin fines
comerciales el "Software - Registro de bienes de CENDITEL", sin garantía
alguna, preservando el reconocimiento moral de los autores y manteniendo los mismos principios
para las obras derivadas, de conformidad con los términos y condiciones de la licencia de
software de la Fundación CENDITEL.

El software es una creación intelectual necesaria para el desarrollo económico y social
de la nación, por tanto, esta licencia tiene la pretensión de preservar la libertad de
este conocimiento para que contribuya a la consolidación de la soberanía nacional.

Cada vez que copie y distribuya el "Software - Registro de bienes de CENDITEL"
debe acompañarlo de una copia de la licencia. Para más información sobre los términos y condiciones
de la licencia visite la siguiente dirección electrónica:
http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/
"""
## @namespace base.urls
#
# Contiene las rutas de uso general en el sistema
# @author William Páez (wpaez at cenditel.gob.ve)
# @author <a href='http://www.cenditel.gob.ve'>Centro Nacional de Desarrollo e Investigación en Tecnologías Libres
# (CENDITEL) nodo Mérida - Venezuela</a>
# @author <a href='www.cida.gob.ve/'>Centro de Investigaciones de Astronomía "Francisco J. Duarte"</a>
# @copyright <a href='http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/'>Licencia de Software CENDITEL versión 1.2</a>
# @date 24-05-2017
# @version 1.0

from __future__ import unicode_literals
from django.urls import path, re_path
from .views import HomeView, Error403View
from .ajax import ComboUpdateView
from django.contrib.auth.decorators import login_required

app_name = 'base'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('error-403/', Error403View.as_view(), name = "error_403"),
]

## URLs de peticiones AJAX
urlpatterns += [
    re_path(r'^ajax/actualizar-combo/?$', login_required(ComboUpdateView.as_view()), name='combo_update'),
]

vivienda/grupo_familiar/persona/urls.py
"""
Nombre del software: SIGETP

Descripción: Sistema Integrado de Información y Documentación Geoestadística y Tecnopolítica

Nombre del licenciante y año: Fundación CIDA (2017)

Autores: William Páez

La Fundación Centro Nacional de Desarrollo e Investigación en Tecnologías Libres (CENDITEL),
ente adscrito al Ministerio del Poder Popular para Educación Universitaria, Ciencia y Tecnología
(MPPEUCT), concede permiso para usar, copiar, modificar y distribuir libremente y sin fines
comerciales el "Software - Registro de bienes de CENDITEL", sin garantía
alguna, preservando el reconocimiento moral de los autores y manteniendo los mismos principios
para las obras derivadas, de conformidad con los términos y condiciones de la licencia de
software de la Fundación CENDITEL.

El software es una creación intelectual necesaria para el desarrollo económico y social
de la nación, por tanto, esta licencia tiene la pretensión de preservar la libertad de
este conocimiento para que contribuya a la consolidación de la soberanía nacional.

Cada vez que copie y distribuya el "Software - Registro de bienes de CENDITEL"
debe acompañarlo de una copia de la licencia. Para más información sobre los términos y condiciones
de la licencia visite la siguiente dirección electrónica:
http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/
"""
## @namespace persona.urls
#
# Contiene las rutas de la aplicación persona
# @author William Páez (wpaez at cenditel.gob.ve)
# @author <a href='http://www.cenditel.gob.ve'>Centro Nacional de Desarrollo e Investigación en Tecnologías Libres
# (CENDITEL) nodo Mérida - Venezuela</a>
# @author <a href='www.cida.gob.ve/'>Centro de Investigaciones de Astronomía "Francisco J. Duarte"</a>
# @copyright <a href='http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/'>Licencia de Software CENDITEL versión 1.2</a>
# @date 24-05-2017
# @version 1.0

from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import (
    PersonaList, PersonaCreate, PersonaUpdate, PersonaDelete
)

urlpatterns = [

    path('', login_required(PersonaList.as_view()), name='persona_lista'),
    path('registro/', login_required(PersonaCreate.as_view()), name='persona_registro'),
    path('actualizar/<int:pk>/', login_required(PersonaUpdate.as_view()), name='persona_actualizar'),
    path('eliminar/<int:pk>/', login_required(PersonaDelete.as_view()), name='persona_eliminar'),
]

vivienda/grupo_familiar/persona/models.py
"""
Nombre del software: SIGETP

Descripción: Sistema Integrado de Información y Documentación Geoestadística y Tecnopolítica

Nombre del licenciante y año: Fundación CIDA (2017)

Autores: William Páez

La Fundación Centro Nacional de Desarrollo e Investigación en Tecnologías Libres (CENDITEL),
ente adscrito al Ministerio del Poder Popular para Educación Universitaria, Ciencia y Tecnología
(MPPEUCT), concede permiso para usar, copiar, modificar y distribuir libremente y sin fines
comerciales el "Software - Registro de bienes de CENDITEL", sin garantía
alguna, preservando el reconocimiento moral de los autores y manteniendo los mismos principios
para las obras derivadas, de conformidad con los términos y condiciones de la licencia de
software de la Fundación CENDITEL.

El software es una creación intelectual necesaria para el desarrollo económico y social
de la nación, por tanto, esta licencia tiene la pretensión de preservar la libertad de
este conocimiento para que contribuya a la consolidación de la soberanía nacional.

Cada vez que copie y distribuya el "Software - Registro de bienes de CENDITEL"
debe acompañarlo de una copia de la licencia. Para más información sobre los términos y condiciones
de la licencia visite la siguiente dirección electrónica:
http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/
"""
## @namespace persona.models
#
# Contiene las clases, atributos y métodos para los modelos a implementar en la aplicación persona
# @author William Páez (wpaez at cenditel.gob.ve)
# @author <a href='http://www.cenditel.gob.ve'>Centro Nacional de Desarrollo e Investigación en Tecnologías Libres
# (CENDITEL) nodo Mérida - Venezuela</a>
# @author <a href='www.cida.gob.ve/'>Centro de Investigaciones de Astronomía "Francisco J. Duarte"</a>
# @copyright <a href='http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/'>Licencia de Software CENDITEL versión 1.2</a>
# @date 24-05-2017
# @version 1.0

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core import validators
from base.constant import (
    SEXO, PARENTESCO, ESTADO_CIVIL, GRADO_INSTRUCCION, MISION_EDUCATIVA, TIPO_INGRESO, MISION_SOCIAL
)
from vivienda.grupo_familiar.models import GrupoFamiliar
import datetime

# Create your models here.

class Persona(models.Model):
    """!
    Clase que contiene los datos de las personas

    @author William Páez (wpaez at cenditel.gob.ve)
    @copyright <a href='http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/'>Licencia de Software CENDITEL versión 1.2</a>
    @date 24-05-2017
    """

    ## Nombre de la Persona
    nombre = models.CharField(max_length=100)

    ## Apellido de la Persona
    apellido = models.CharField(max_length=100)

    ## Cédula de la Persona. Si tiene o no
    cedula = models.CharField(
        max_length=9,
        unique=True,
        null=True
    )

    # +058-416-0708340
    telefono = models.CharField(
        max_length=18,
    )

    ## Establece el correo de la persona
    correo = models.CharField(
        max_length=100, help_text=("correo@correo.com")
    )

    ## Establece el sexo de la Persona
    sexo = models.CharField(max_length=1, choices=SEXO)

    ## Establece la fecha de nacimiento de la Persona
    fecha_nacimiento = models.DateField()

    ## Establece el parentesto que tiene el jefe familiar con el resto del Grupo Familiar
    parentesco = models.CharField(max_length=2, choices=PARENTESCO)

    ## Estalece si la persona es jefe familiar o no
    jefe_familiar = models.BooleanField()

    ## Establece el Estado Civil de la Persona
    estado_civil = models.CharField(max_length=2, choices=ESTADO_CIVIL)

    ## Establece el Grado de Instrucción de la Persona
    grado_instruccion = models.CharField(max_length=2, choices=GRADO_INSTRUCCION)

    ## Establece la Misión Educativa que tiene la Persona
    mision_educativa = models.CharField(max_length=2, choices=MISION_EDUCATIVA)

    ## Establece la Misión Social ue tiene la Persona
    mision_social = models.CharField(max_length=2, choices=MISION_SOCIAL)

    ## Establece la Profesión de la Persona (sin categoria de momento)
    profesion = models.CharField(max_length=100)

    ## Establece la Ocupación de la Persona (sin categoria de momento)
    ocupacion = models.CharField(max_length=100)

    ## Establece el Lugar de trabajo de la persona
    lugar_trabajo = models.CharField(max_length=100)

    ## Establece los ingresos de dinero de la Persona
    ingreso = models.CharField(max_length=100, choices=TIPO_INGRESO)

    ## Establece si la persona tiene o no ingresos por ser pensionado
    pensionado = models.BooleanField()

    ## Establece si la persona tiene o no ingresos por ser jubilado
    jubilado = models.BooleanField()

    ## Establece el Deporte que practica la Persona (sin categoria de momento)
    deporte = models.CharField(max_length=100)

    ## Establece la Enfermedad que presenta la Persona
    enfermedad = models.CharField(max_length=500)

    ## Establece la Discapacidad que tiene la Persona
    discapacidad = models.CharField(max_length=500)

    ## Establece si la Persona ha leido la ley de los consejos comunales
    ley_consejo_comunal = models.BooleanField(default=False)

    ## Establece que cursos le gustaría hacer a la Persona (sin categoria de momento)
    curso = models.CharField(max_length=100)

    ## Establece todas las organizaciones que la Persona conoce (las preguntas de arriba se redondean en esta)
    organizacion_comunitaria = models.CharField(max_length=500)

    ## Estable que hace la Persona en sus horas de ocio
    ocio = models.CharField(max_length=500)

    ## Estable la sugerencia que la Persona ofrece para poder mejorar la Comunicación en la Comunidad
    mejorar_comunicacion = models.CharField(max_length=500)

    ## Establece la Inseguridad que la Persona considera que hay en la comunidad
    inseguridad = models.CharField(max_length=500)

    ## Establece algún comentario que la Persona quiera hacer en relación a las necesidades de la comunidad
    comentario = models.CharField(max_length=500)

    ## Establece alguna observación que se tenga sobre la persona
    observacion = models.TextField()

    ## Establece la relación con el grupo familiar
    grupo_familiar = models.ForeignKey(GrupoFamiliar,on_delete=models.CASCADE)

    ## Cacula la edad en años que tiene una persona según su fecha de nacimiento
    def edad(self):
        """!
        Método que calcula la edad de la persona

        @author William Páez (wpaez at cenditel.gob.ve)
        @copyright <a href='http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/'>Licencia de Software CENDITEL versión 1.2</a>
        @date 24-05-2017
        @param self <b>{object}</b> Objeto que instancia la clase
        @return Retorna un número entero que representa la edad
        """

        return int((datetime.date.today() - self.fecha_nacimiento).days / 365.25  )

    def __str__(self):
        """!
        Método para representar la clase de forma amigable

        @author William Páez (wpaez at cenditel.gob.ve)
        @copyright <a href='http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/'>Licencia de Software CENDITEL versión 1.2</a>
        @date 14-01-2018
        @param self <b>{object}</b> Objeto que instancia la clase
        @return Devuelve una cadena de caracteres con el nombre, apellido y cédula de la persona
        """

        return self.nombre + ' ' + self.apellido + ', ' + str(self.cedula)

vivienda/grupo_familiar/persona/templates/persona.eliminar.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block content_header_title %}{% trans 'Persona' %}{% endblock %}
{% block content_header_roadmap %}
    <li><a href="{% url 'vivienda_lista' %}">{% trans 'Vivienda' %}</a></li>
    <li><a href="{% url 'grupo_familiar_lista' %}">{% trans 'Grupo Familiar' %}</a></li>
    <li><a href="{% url 'persona_lista' %}">{% trans 'Persona' %}</a></li>
    <li class="active">{% trans 'Eliminar' %}</li>
{% endblock %}
{% block contenido %}
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Eliminar</h3>
        </div>
        <div class="box-body">
            <form method="post">
                {% csrf_token %}
                <p>¿Estás seguro que deseas eliminar los datos de la Persona "{{ object.nombre }} {{ object.apellido }}"?</p>
                <div class="box-footer text-right">
                    <a href="{% url 'persona_lista' %}" class="btn btn-primary btn-sm">Atrás</a>
                    <button type="submit" class="btn btn-danger btn-sm" data-toggle="tooltip">{% trans 'Eliminar' %}</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

vivienda/grupo_familiar/persona/templates/persona.lista.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block content_header_title %}{% trans 'Persona' %}{% endblock %}
{% block content_header_roadmap %}
    <li><a href="{% url 'vivienda_lista' %}">{% trans 'Vivienda' %}</a></li>
    <li><a href="{% url 'grupo_familiar_lista' %}">{% trans 'Grupo Familiar' %}</a></li>
    <li class="active">{% trans 'Persona' %}</li>
{% endblock %}
{% block contenido %}
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Listar</h3><br>
        </div>

        <div class="box-header">
            <a href="{% url 'persona_registro' %}" class="btn btn-success pull-left">Registrar</a>
        </div>

        <div class="box-body">
            <div class="row box-body table-responsive">
                <!--<div class="col-md-12 col-sm-12 col-xs-12">-->
                    <table class="table table-striped table-hover table-bordered display dataTable blue-table" id="table" style="width:6300px;">
                        <thead>
                            <tr>
                                <th>Grupo Familiar</th>
                                <th>Nombres</th>
                                <th>Apellidos</th>
                                <th>Cédula</th>
                                <th>Teléfono</th>
                                <th>correo</th>
                                <th>Sexo</th>
                                <th>Fecha de nacimiento</th>
                                <th>Edad</th>
                                <th>Parentesco</th>
                                <th>Jefe Familiar</th>
                                <th>Estado civil</th>
                                <th>Grado de instrucción</th>
                                <th>Misión Educativa</th>
                                <th>Misión Social</th>
                                <th>Profesión</th>
                                <th>Ocupación</th>
                                <th>Lugar de Trabajo</th>
                                <th>Ingresos</th>
                                <th>Pensionado</th>
                                <th>Jubilado</th>
                                <th>Deporte que practica</th>
                                <th>Enfermedad que presenta</th>
                                <th>Discapacidad que presenta</th>
                                <th>¿Ha leído la ley de consejos comunales?</th>
                                <th>¿Qué cursos le gustaría hacer?</th>
                                <th>¿Qué organizaciones comunitarias conoce?</th>
                                <th>¿Qué hace en sus horas de ocio?</th>
                                <th>¿Qué sugiere Ud. para mejorar la comunicación en la comunidad?</th>
                                <th>¿Qué inseguridad presenta la comunidad?</th>
                                <th>Algún comentario que desee hacer en relación a las necesidades y soluciones en la comunidad</th>
                                <th>Observación</th>
                                <th>Operación</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for persona in object_list %}
                                <tr>
                                <td>{{ persona.grupo_familiar }}</td>
                                <td>{{ persona.nombre }} </td>
                                <td>{{ persona.apellido }}</td>
                                {% if persona.cedula %}
                                    <td>{{ persona.cedula }}</td>
                                {% else %}
                                    <td></td>
                                {% endif %}
                                <td>{{ persona.telefono }}</td>
                                <td>{{ persona.correo }}</td>
                                <td>{{ persona.get_sexo_display }}</td>
                                <td>{{ persona.fecha_nacimiento }}</td>
                                <td>{{ persona.edad }}</td>
                                <td>{{ persona.get_parentesco_display }}</td>
                                {% if persona.jefe_familiar %}
                                    <td>Si</td>
                                {% else %}
                                    <td>No</td>
                                {% endif %}
                                <td>{{ persona.get_estado_civil_display }}</td>
                                <td>{{ persona.get_grado_instruccion_display }}</td>
                                <td>{{ persona.get_mision_educativa_display }}</td>
                                <td>{{ persona.get_mision_social_display }}</td>
                                <td>{{ persona.profesion }}</td>
                                <td>{{ persona.ocupacion }}</td>
                                <td>{{ persona.lugar_trabajo }}</td>
                                <td>{{ persona.get_ingreso_display }}</td>
                                {% if persona.pensionado %}
                                    <td>Si</td>
                                {% else %}
                                    <td>No</td>
                                {% endif %}
                                {% if persona.jubilado %}
                                    <td>Si</td>
                                {% else %}
                                    <td>No</td>
                                {% endif %}
                                <td>{{ persona.deporte }}</td>
                                <td>{{ persona.enfermedad }}</td>
                                <td>{{ persona.discapacidad }}</td>
                                {% if persona.ley_consejo_comunal %}
                                    <td>Si</td>
                                {% else %}
                                    <td>No</td>
                                {% endif %}
                                <td>{{ persona.curso }}</td>
                                <td>{{ persona.organizacion_comunitaria }}</td>
                                <td>{{ persona.ocio }}</td>
                                <td>{{ persona.mejorar_comunicacion }}</td>
                                <td>{{ persona.inseguridad }}</td>
                                <td>{{ persona.comentario }}</td>
                                <td>{{ persona.observacion }}</td>
                                <td> <a href="{% url 'persona_actualizar' persona.id %}" data-toggle="tooltip" title="Actualizar"><i class="fa fa-pencil"></i></a> <a href="{% url 'persona_eliminar' persona.id %}" data-toggle="tooltip" title="Eliminar"><i class="fa fa-remove"></i</a> </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                <!--</div>-->
            </div>
        </div>
    </div>
{% endblock %}
{% block extra_footer %}
    <script type="text/javascript">
        $(document).ready(function() {
            var table = $('#table').DataTable({
                "autoWidth": false,
                "columnDefs": [
                    { "width": "200px", "targets": 0 },
                    { "width": "250px", "targets": 1 },
                    { "width": "250px", "targets": 2 },
                    { "width": "150px", "targets": 3 },
                    { "width": "150px", "targets": 4 },
                    { "width": "250px", "targets": 5 },
                    { "width": "100px", "targets": 6 },
                    { "width": "100px", "targets": 7 },
                    { "width": "100px", "targets": 8 },
                    { "width": "150px", "targets": 9 },
                    { "width": "100px", "targets": 10 },
                    { "width": "150px", "targets": 11 },
                    { "width": "150px", "targets": 12 },
                    { "width": "150px", "targets": 13 },
                    { "width": "150px", "targets": 14 },
                    { "width": "200px", "targets": 15 },
                    { "width": "200px", "targets": 16 },
                    { "width": "200px", "targets": 17 },
                    { "width": "150px", "targets": 18 },
                    { "width": "150px", "targets": 19 },
                    { "width": "150px", "targets": 20 },
                    { "width": "250px", "targets": 21 },
                    { "width": "250px", "targets": 22 },
                    { "width": "250px", "targets": 23 },
                    { "width": "250px", "targets": 24 },
                    { "width": "250px", "targets": 25 },
                    { "width": "250px", "targets": 26 },
                    { "width": "250px", "targets": 27 },
                    { "width": "250px", "targets": 28 },
                    { "width": "250px", "targets": 29 },
                    { "width": "400px", "targets": 30 },
                    { "width": "300px", "targets": 31 },
                    { "width": "100px", "targets": 32 },
                ],
            });

            button_datatable(table);
        });
    </script>
{% endblock %}