base/urls.py
"""
Nombre del software: SIGETP

Descripción: Sistema Integrado de Información y Documentación Geoestadística y Tecnopolítica

Nombre del licenciante y año: Fundación CIDA (2017)

Autores: William Páez

La Fundación Centro Nacional de Desarrollo e Investigación en Tecnologías Libres (CENDITEL),
ente adscrito al Ministerio del Poder Popular para Educación Universitaria, Ciencia y Tecnología
(MPPEUCT), concede permiso para usar, copiar, modificar y distribuir libremente y sin fines
comerciales el "Software - Registro de bienes de CENDITEL", sin garantía
alguna, preservando el reconocimiento moral de los autores y manteniendo los mismos principios
para las obras derivadas, de conformidad con los términos y condiciones de la licencia de
software de la Fundación CENDITEL.

El software es una creación intelectual necesaria para el desarrollo económico y social
de la nación, por tanto, esta licencia tiene la pretensión de preservar la libertad de
este conocimiento para que contribuya a la consolidación de la soberanía nacional.

Cada vez que copie y distribuya el "Software - Registro de bienes de CENDITEL"
debe acompañarlo de una copia de la licencia. Para más información sobre los términos y condiciones
de la licencia visite la siguiente dirección electrónica:
http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/
"""
## @namespace base.urls
#
# Contiene las rutas de uso general en el sistema
# @author William Páez (wpaez at cenditel.gob.ve)
# @author <a href='http://www.cenditel.gob.ve'>Centro Nacional de Desarrollo e Investigación en Tecnologías Libres
# (CENDITEL) nodo Mérida - Venezuela</a>
# @author <a href='www.cida.gob.ve/'>Centro de Investigaciones de Astronomía "Francisco J. Duarte"</a>
# @copyright <a href='http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/'>Licencia de Software CENDITEL versión 1.2</a>
# @date 24-05-2017
# @version 1.0

from __future__ import unicode_literals
from django.urls import path, re_path
from .views import HomeView, Error403View
from .ajax import ComboUpdateView
from django.contrib.auth.decorators import login_required

app_name = 'base'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('error-403/', Error403View.as_view(), name = "error_403"),
]

## URLs de peticiones AJAX
urlpatterns += [
    re_path(r'^ajax/actualizar-combo/?$', login_required(ComboUpdateView.as_view()), name='combo_update'),
]

vivienda/grupo_familiar/persona/urls.py
"""
Nombre del software: SIGETP

Descripción: Sistema Integrado de Información y Documentación Geoestadística y Tecnopolítica

Nombre del licenciante y año: Fundación CIDA (2017)

Autores: William Páez

La Fundación Centro Nacional de Desarrollo e Investigación en Tecnologías Libres (CENDITEL),
ente adscrito al Ministerio del Poder Popular para Educación Universitaria, Ciencia y Tecnología
(MPPEUCT), concede permiso para usar, copiar, modificar y distribuir libremente y sin fines
comerciales el "Software - Registro de bienes de CENDITEL", sin garantía
alguna, preservando el reconocimiento moral de los autores y manteniendo los mismos principios
para las obras derivadas, de conformidad con los términos y condiciones de la licencia de
software de la Fundación CENDITEL.

El software es una creación intelectual necesaria para el desarrollo económico y social
de la nación, por tanto, esta licencia tiene la pretensión de preservar la libertad de
este conocimiento para que contribuya a la consolidación de la soberanía nacional.

Cada vez que copie y distribuya el "Software - Registro de bienes de CENDITEL"
debe acompañarlo de una copia de la licencia. Para más información sobre los términos y condiciones
de la licencia visite la siguiente dirección electrónica:
http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/
"""
## @namespace persona.urls
#
# Contiene las rutas de la aplicación persona
# @author William Páez (wpaez at cenditel.gob.ve)
# @author <a href='http://www.cenditel.gob.ve'>Centro Nacional de Desarrollo e Investigación en Tecnologías Libres
# (CENDITEL) nodo Mérida - Venezuela</a>
# @author <a href='www.cida.gob.ve/'>Centro de Investigaciones de Astronomía "Francisco J. Duarte"</a>
# @copyright <a href='http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/'>Licencia de Software CENDITEL versión 1.2</a>
# @date 24-05-2017
# @version 1.0

from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import (
    PersonaList, PersonaCreate, PersonaUpdate, PersonaDelete
)

urlpatterns = [

    path('', login_required(PersonaList.as_view()), name='persona_lista'),
    path('registro/', login_required(PersonaCreate.as_view()), name='persona_registro'),
    path('actualizar/<int:pk>/', login_required(PersonaUpdate.as_view()), name='persona_actualizar'),
    path('eliminar/<int:pk>/', login_required(PersonaDelete.as_view()), name='persona_eliminar'),
]

vivienda/grupo_familiar/urls.py
"""
Nombre del software: SIGETP

Descripción: Sistema Integrado de Información y Documentación Geoestadística y Tecnopolítica

Nombre del licenciante y año: Fundación CIDA (2017)

Autores: William Páez

La Fundación Centro Nacional de Desarrollo e Investigación en Tecnologías Libres (CENDITEL),
ente adscrito al Ministerio del Poder Popular para Educación Universitaria, Ciencia y Tecnología
(MPPEUCT), concede permiso para usar, copiar, modificar y distribuir libremente y sin fines
comerciales el "Software - Registro de bienes de CENDITEL", sin garantía
alguna, preservando el reconocimiento moral de los autores y manteniendo los mismos principios
para las obras derivadas, de conformidad con los términos y condiciones de la licencia de
software de la Fundación CENDITEL.

El software es una creación intelectual necesaria para el desarrollo económico y social
de la nación, por tanto, esta licencia tiene la pretensión de preservar la libertad de
este conocimiento para que contribuya a la consolidación de la soberanía nacional.

Cada vez que copie y distribuya el "Software - Registro de bienes de CENDITEL"
debe acompañarlo de una copia de la licencia. Para más información sobre los términos y condiciones
de la licencia visite la siguiente dirección electrónica:
http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/
"""
## @namespace grupo_familiar.urls
#
# Contiene las rutas de la aplicación grupo_familiar
# @author William Páez (wpaez at cenditel.gob.ve)
# @author <a href='http://www.cenditel.gob.ve'>Centro Nacional de Desarrollo e Investigación en Tecnologías Libres
# (CENDITEL) nodo Mérida - Venezuela</a>
# @author <a href='www.cida.gob.ve/'>Centro de Investigaciones de Astronomía "Francisco J. Duarte"</a>
# @copyright <a href='http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/'>Licencia de Software CENDITEL versión 1.2</a>
# @date 24-05-2017
# @version 1.0

from django.urls import path, include
from django.contrib.auth.decorators import login_required

from .views import (
    GrupoFamiliarList,GrupoFamiliarCreate,GrupoFamiliarUpdate,GrupoFamiliarDelete
)

urlpatterns = [

    path('', login_required(GrupoFamiliarList.as_view()), name='grupo_familiar_lista'),
    path('registro/', login_required(GrupoFamiliarCreate.as_view()), name='grupo_familiar_registro'),
    path('actualizar/<int:pk>/', login_required(GrupoFamiliarUpdate.as_view()), name='grupo_familiar_actualizar'),
    path('eliminar/<int:pk>/', login_required(GrupoFamiliarDelete.as_view()), name='grupo_familiar_eliminar'),
    path('persona/', include('vivienda.grupo_familiar.persona.urls')),
]

vivienda/grupo_familiar/models.py
"""
Nombre del software: SIGETP

Descripción: Sistema Integrado de Información y Documentación Geoestadística y Tecnopolítica

Nombre del licenciante y año: Fundación CIDA (2017)

Autores: William Páez

La Fundación Centro Nacional de Desarrollo e Investigación en Tecnologías Libres (CENDITEL),
ente adscrito al Ministerio del Poder Popular para Educación Universitaria, Ciencia y Tecnología
(MPPEUCT), concede permiso para usar, copiar, modificar y distribuir libremente y sin fines
comerciales el "Software - Registro de bienes de CENDITEL", sin garantía
alguna, preservando el reconocimiento moral de los autores y manteniendo los mismos principios
para las obras derivadas, de conformidad con los términos y condiciones de la licencia de
software de la Fundación CENDITEL.

El software es una creación intelectual necesaria para el desarrollo económico y social
de la nación, por tanto, esta licencia tiene la pretensión de preservar la libertad de
este conocimiento para que contribuya a la consolidación de la soberanía nacional.

Cada vez que copie y distribuya el "Software - Registro de bienes de CENDITEL"
debe acompañarlo de una copia de la licencia. Para más información sobre los términos y condiciones
de la licencia visite la siguiente dirección electrónica:
http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/
"""
## @namespace grupo_familiar.models
#
# Contiene las clases, atributos y métodos para los modelos a implementar en la aplicación grupo_familiar
# @author William Páez (wpaez at cenditel.gob.ve)
# @author <a href='http://www.cenditel.gob.ve'>Centro Nacional de Desarrollo e Investigación en Tecnologías Libres
# (CENDITEL) nodo Mérida - Venezuela</a>
# @author <a href='www.cida.gob.ve/'>Centro de Investigaciones de Astronomía "Francisco J. Duarte"</a>
# @copyright <a href='http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/'>Licencia de Software CENDITEL versión 1.2</a>
# @date 24-05-2017
# @version 1.0

from django.db import models
from base.constant import TIPO_TENENCIA
from vivienda.models import Vivienda
# Create your models here.

class GrupoFamiliar(models.Model):
    """!
    Clase que contiene los datos de los grupos familiares

    @author William Páez (wpaez at cenditel.gob.ve)
    @copyright <a href='http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/'>Licencia de Software CENDITEL versión 1.2</a>
    @date 24-05-2017
    """

    ## Apellido del grupo familiar
    apellido_familia = models.CharField(max_length=100)

    ## Familia beneficiada por clap
    familia_beneficiada = models.BooleanField(default=False)

    ## Tenencia que el grupo familiar tiene sobre la vivienda
    tenencia = models.CharField(max_length=2, choices=TIPO_TENENCIA)

    ## Alquiler de la vivienda en meses
    alquilada = models.IntegerField(default=0)

    ## Consulta sobre el pasaje
    pasaje = models.BooleanField(default=False)

    ## Observación
    observacion = models.TextField()

    ## Establece la relación del grupo familiar con la vivienda
    vivienda = models.ForeignKey(Vivienda,on_delete=models.CASCADE)

    def __str__(self):
        """!
        Método para representar la clase de forma amigable

        @author William Páez (wpaez at cenditel.gob.ve)
        @copyright <a href='http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/'>Licencia de Software CENDITEL versión 1.2</a>
        @date 14-01-2018
        @param self <b>{object}</b> Objeto que instancia la clase
        @return Devuelve una cadena de caracteres con el apellido de la familia y el id del grupo familiar
        """

        return self.apellido_familia + ' | ' + str(self.id)

vivienda/grupo_familiar/templates/grupo.familiar.eliminar.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block content_header_title %}{% trans 'Grupo Familiar' %}{% endblock %}
{% block content_header_roadmap %}
    <li><a href="{% url 'vivienda_lista' %}">{% trans 'Vivienda' %}</a></li>
    <li><a href="{% url 'grupo_familiar_lista' %}">{% trans 'Grupo Familiar' %}</a></li>
    <li class="active">{% trans 'Eliminar' %}</li>
{% endblock %}
{% block contenido %}
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Eliminar</h3>
        </div>
        <div class="box-body">
            <form method="post">
                {% csrf_token %}
                <p>¿Estás seguro que deseas eliminar los datos del Grupo Familiar "{{ object.apellido_familia }}-{{ object.id }}"?</p>
                <div class="box-footer text-right">
                    <a href="{% url 'grupo_familiar_lista' %}" class="btn btn-primary btn-sm">Atrás</a>
                    <button type="submit" class="btn btn-danger btn-sm" data-toggle="tooltip">{% trans 'Eliminar' %}</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

vivienda/grupo_familiar/templates/grupo.familiar.lista.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block content_header_title %}{% trans 'Grupo Familiar' %}{% endblock %}
{% block content_header_roadmap %}
    <li><a href="{% url 'vivienda_lista' %}">{% trans 'Vivienda' %}</a></li>
    <li class="active">{% trans 'Grupo Familiar' %}</li>
{% endblock %}
{% block contenido %}
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Listar</h3><br>
        </div>

        <div class="box-header">
            <a href="{% url 'grupo_familiar_registro' %}" class="btn btn-success pull-left">Registrar</a>
        </div>

        <div class="box-body">
            <div class="row box-body table-responsive">
                <!--<div class="col-md-12 col-sm-12 col-xs-12">-->
                    <table class="table table-striped table-hover table-bordered display dataTable blue-table" id="table" style="width:1750px;">
                        <thead>
                            <tr>
                                <th>Vivienda</th>
                                <th>Apellido de la Familia</th>
                                <th>¿La Familia ha sido beneficiada por el CLAP?</th>
                                <th>Tipo de Tenencia</th>
                                <th> Tiempo de Alquiler (Meses) </th>
                                <th>¿Cree Ud. que se deba consultar a las comunidades para los precios del pasaje?</th>
                                <th>Observación</th>
                                <th>Operación</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for grupo_familiar in object_list %}
                                <tr>
                                <td> {{ grupo_familiar.vivienda }} </td>
                                <td> {{ grupo_familiar }} </td>

                                {% if grupo_familiar.familia_beneficiada %}
                                    <td> Si </td>
                                {% else %}
                                    <td> No </td>
                                {% endif %}

                                {% if grupo_familiar.tenencia == 'AL' %}
                                    <td> {{ grupo_familiar.get_tenencia_display }} </td>
                                    <td> {{ grupo_familiar.alquilada }} </td>
                                {% else %}
                                    <td> {{ grupo_familiar.get_tenencia_display }} </td>
                                    <td> </td>
                                {% endif %}

                                {% if grupo_familiar.pasaje %}
                                    <td> Si </td>
                                {% else %}
                                    <td> No </td>
                                {% endif %}

                                <td> {{ grupo_familiar.observacion }} </td>

                                <td> <a href="{% url 'grupo_familiar_actualizar' grupo_familiar.id %}" data-toggle="tooltip" title="Actualizar"><i class="fa fa-pencil"></i></a> <a href="{% url 'grupo_familiar_eliminar' grupo_familiar.id %}" data-toggle="tooltip" title="Eliminar"><i class="fa fa-remove"></i></a> </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                <!--</div>-->
            </div>
        </div>
    </div>
{% endblock %}
{% block extra_footer %}
    <script type="text/javascript">
        $(document).ready(function() {
            var table = $('#table').DataTable({
                "autoWidth": false,
                "columnDefs": [
                    { "width": "200px", "targets": 0 },
                    { "width": "200px", "targets": 1 },
                    { "width": "200px", "targets": 2 },
                    { "width": "200px", "targets": 3 },
                    { "width": "200px", "targets": 4 },
                    { "width": "350px", "targets": 5 },
                    { "width": "300px", "targets": 6 },
                    { "width": "100px", "targets": 7 },
                ],
            });

            button_datatable(table);
        });
    </script>
{% endblock %}

vivienda/grupo_familiar/templates/grupo.familiar.registro.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block content_header_title %}{% trans 'Grupo Familiar' %}{% endblock %}
{% block content_header_roadmap %}
    <li><a href="{% url 'vivienda_lista' %}">{% trans 'Vivienda' %}</a></li>
    <li><a href="{% url 'grupo_familiar_lista' %}">{% trans 'Grupo Familiar' %}</a></li>
    <li class="active">{% if not form.instance.pk %}{% trans 'Registro' %}{% else %}{% trans 'Actualizar' %}{% endif %}</li>
{% endblock %}
{% block contenido %}
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">{% if not form.instance.pk %}{% trans 'Registrar' %}{% else %}{% trans 'Actualizar' %}{% endif %}</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
	        <form action="" role="form" class="form form-horizontal validate-form" method="post" autocomplete="off">
            {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="form-group {% if form.vivienda.errors %}has-error{% endif %}">
                                <label class="col-md-3 col-xs-3 col-sm-3 control-label" for="{{ form.vivienda.auto_id }}">
                                    {{ form.vivienda.label }}
                                </label>
                                <div class="col-md-9 col-xs-9 col-sm-9">
                                    <div class="form-inline">
                                        {{ form.vivienda }}
                                        <i class="ion ion-ios-medical item-requerido"></i>
                                    </div>
                                    {% include 'base/form.errors.html' with form_errors=form.vivienda.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="form-group {% if form.apellido_familia.errors %}has-error{% endif %}">
                                <label class="col-md-3 col-xs-3 col-sm-3 control-label" for="{{ form.apellido_familia.auto_id }}">
                                    {{ form.apellido_familia.label }}
                                </label>
                                <div class="col-md-9 col-xs-9 col-sm-9">
                                    <div class="form-inline">
                                        {{ form.apellido_familia }}
                                        <i class="ion ion-ios-medical item-requerido"></i>
                                    </div>
                                    {% include 'base/form.errors.html' with form_errors=form.apellido_familia.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="form-group {% if form.tenencia.errors %}has-error{% endif %}">
                                <label class="col-md-3 col-xs-3 col-sm-3 control-label" for="{{ form.tenencia.auto_id }}">
                                    {{ form.tenencia.label }}
                                </label>
                                <div class="col-md-9 col-xs-9 col-sm-9">
                                    <div class="form-inline">
                                        {{ form.tenencia }}
                                        <i class="ion ion-ios-medical item-requerido"></i>
                                    </div>
                                    {% include 'base/form.errors.html' with form_errors=form.tenencia.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
                                </div>
                            </div>
                        </div>
                        <div id="bloque_alquilada" class="invisible">
                            <div class="col-md-6 col-sm-6 col-xs-6">
                                <div class="form-group {% if form.alquilada.errors %}has-error{% endif %}">
                                    <label class="col-md-3 col-xs-3 col-sm-3 control-label" for="{{ form.alquilada.auto_id }}">
                                        {{ form.alquilada.label }}
                                    </label>
                                    <div class="col-md-9 col-xs-9 col-sm-9">
                                        <div class="form-inline">
                                            {{ form.alquilada }}
                                        </div>
                                        {% include 'base/form.errors.html' with form_errors=form.alquilada.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="form-group {% if form.pasaje.errors %}has-error{% endif %}">
                                <label class="col-md-3 col-xs-3 col-sm-3 control-label" for="{{ form.pasaje.auto_id }}">
                                    {{ form.pasaje.label }}
                                </label>
                                <div class="col-md-9 col-xs-9 col-sm-9">
                                    <div class="form-inline">
                                        {{ form.pasaje }}
                                    </div>
                                    {% include 'base/form.errors.html' with form_errors=form.pasaje.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="form-group {% if form.familia_beneficiada.errors %}has-error{% endif %}">
                                <label class="col-md-3 col-xs-3 col-sm-3 control-label" for="{{ form.familia_beneficiada.auto_id }}">
                                    {{ form.familia_beneficiada.label }}
                                </label>
                                <div class="col-md-9 col-xs-9 col-sm-9">
                                    <div class="form-inline">
                                        {{ form.familia_beneficiada }}
                                    </div>
                                    {% include 'base/form.errors.html' with form_errors=form.familia_beneficiada.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <div class="form-group {% if form.observacion.errors %}has-error{% endif %}">
                                <label class="col-md-3 col-xs-3 col-sm-3 control-label" for="{{ form.observacion.auto_id }}">
                                    {{ form.observacion.label }}
                                </label>
                                <div class="col-md-9 col-xs-9 col-sm-9">
                                    <div class="form-inline">
                                        {{ form.observacion }}
                                    </div>
                                    {% include 'base/form.errors.html' with form_errors=form.observacion.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
                                </div>
                            </div>
                        </div>
                    </div>

                <div class="box-footer text-right">
                    <a href="{% url 'grupo_familiar_lista' %}" class="btn btn-primary btn-sm">Atrás</a>
                    <button type="reset" class="btn btn-primary btn-sm" data-toggle="tooltip">{% trans 'Limpiar' %}</button>
                    <button type="submit" class="btn btn-primary btn-sm" data-toggle="tooltip">{% if not form.instance.pk %}{% trans 'Registrar' %}{% else %}{% trans 'Actualizar' %}{% endif %}</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}
{% block extra_footer %}
    <script>
        $(document).ready(function() {
            //mostrar campos dependientes del valor de otros a la hora de actualizar
            var tenencia = $("#id_tenencia").val();
            var ba = $("#bloque_alquilada");
            (tenencia==="AL") ? ba.removeClass('invisible') : ba.addClass('invisible');
        });

        function __tenencia(val)
        {
            if( val == "AL")
            {
                $("#bloque_alquilada").removeClass('invisible');
                $("#id_alquilada").attr('required', 'required');
                $("#id_alquilada").attr('min', '1');
            }
            else
            {
                $("#bloque_alquilada").addClass('invisible');
                $("#id_alquilada").removeAttr('required');
                $("#id_alquilada").attr('min', '0');
                $("#id_alquilada").val(0);
            }
        }
    </script>
{% endblock %}