base/urls.py
"""
Nombre del software: SIGETP

Descripción: Sistema Integrado de Información y Documentación Geoestadística y Tecnopolítica

Nombre del licenciante y año: Fundación CIDA (2017)

Autores: William Páez

La Fundación Centro Nacional de Desarrollo e Investigación en Tecnologías Libres (CENDITEL),
ente adscrito al Ministerio del Poder Popular para Educación Universitaria, Ciencia y Tecnología
(MPPEUCT), concede permiso para usar, copiar, modificar y distribuir libremente y sin fines
comerciales el "Software - Registro de bienes de CENDITEL", sin garantía
alguna, preservando el reconocimiento moral de los autores y manteniendo los mismos principios
para las obras derivadas, de conformidad con los términos y condiciones de la licencia de
software de la Fundación CENDITEL.

El software es una creación intelectual necesaria para el desarrollo económico y social
de la nación, por tanto, esta licencia tiene la pretensión de preservar la libertad de
este conocimiento para que contribuya a la consolidación de la soberanía nacional.

Cada vez que copie y distribuya el "Software - Registro de bienes de CENDITEL"
debe acompañarlo de una copia de la licencia. Para más información sobre los términos y condiciones
de la licencia visite la siguiente dirección electrónica:
http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/
"""
## @namespace base.urls
#
# Contiene las rutas de uso general en el sistema
# @author William Páez (wpaez at cenditel.gob.ve)
# @author <a href='http://www.cenditel.gob.ve'>Centro Nacional de Desarrollo e Investigación en Tecnologías Libres
# (CENDITEL) nodo Mérida - Venezuela</a>
# @author <a href='www.cida.gob.ve/'>Centro de Investigaciones de Astronomía "Francisco J. Duarte"</a>
# @copyright <a href='http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/'>Licencia de Software CENDITEL versión 1.2</a>
# @date 24-05-2017
# @version 1.0

from __future__ import unicode_literals
from django.urls import path, re_path
from .views import HomeView, Error403View
from .ajax import ComboUpdateView
from django.contrib.auth.decorators import login_required

app_name = 'base'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('error-403/', Error403View.as_view(), name = "error_403"),
]

## URLs de peticiones AJAX
urlpatterns += [
    re_path(r'^ajax/actualizar-combo/?$', login_required(ComboUpdateView.as_view()), name='combo_update'),
]

usuario/urls.py
"""
Nombre del software: SIGETP

Descripción: Sistema Integrado de Información y Documentación Geoestadística y Tecnopolítica

Nombre del licenciante y año: Fundación CIDA (2017)

Autores: William Páez

La Fundación Centro Nacional de Desarrollo e Investigación en Tecnologías Libres (CENDITEL),
ente adscrito al Ministerio del Poder Popular para Educación Universitaria, Ciencia y Tecnología
(MPPEUCT), concede permiso para usar, copiar, modificar y distribuir libremente y sin fines
comerciales el "Software - Registro de bienes de CENDITEL", sin garantía
alguna, preservando el reconocimiento moral de los autores y manteniendo los mismos principios
para las obras derivadas, de conformidad con los términos y condiciones de la licencia de
software de la Fundación CENDITEL.

El software es una creación intelectual necesaria para el desarrollo económico y social
de la nación, por tanto, esta licencia tiene la pretensión de preservar la libertad de
este conocimiento para que contribuya a la consolidación de la soberanía nacional.

Cada vez que copie y distribuya el "Software - Registro de bienes de CENDITEL"
debe acompañarlo de una copia de la licencia. Para más información sobre los términos y condiciones
de la licencia visite la siguiente dirección electrónica:
http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/
"""
## @namespace usuario.urls
#
# Contiene las rutas de la aplicación usuario
# @author William Páez (wpaez at cenditel.gob.ve)
# @author <a href='http://www.cenditel.gob.ve'>Centro Nacional de Desarrollo e Investigación en Tecnologías Libres
# (CENDITEL) nodo Mérida - Venezuela</a>
# @author <a href='www.cida.gob.ve/'>Centro de Investigaciones de Astronomía "Francisco J. Duarte"</a>
# @copyright <a href='http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/'>Licencia de Software CENDITEL versión 1.2</a>
# @date 24-05-2017
# @version 1.0

from django.urls import path, include
from .views import CommunalUpdateView, PollsterListView, PollsterCreateView, PollsterUpdateView, PollsterStatusUpdateView
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

app_name = 'usuario'

urlpatterns = [

    path('login/', auth_views.LoginView.as_view(template_name='usuario/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('reset/password_reset/', auth_views.PasswordResetView.as_view(template_name='usuario/password_reset_form.html',
        email_template_name='password_reset_email.html'),
        name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='usuario/password_reset_done.html'),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='usuario/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='usuario/password_reset_complete.html'),
        name='password_reset_complete'),
    path('cambiar-clave/', auth_views.PasswordChangeView.as_view(template_name='usuario/password_change_form.html'), name='password_change'),
    path('cambiar-clave-hecho/', auth_views.PasswordChangeDoneView.as_view(template_name='usuario/password_change_done.html'), name='password_change_done'),

    path('comunal/actualizar/<int:pk>/', login_required(CommunalUpdateView.as_view()), name='communal_update'),

    path('encuestador/listar/', login_required(PollsterListView.as_view()), name='pollster_list'),
    path('encuestador/registrar/', login_required(PollsterCreateView.as_view()), name='pollster_create'),
    path('encuestador/actualizar/<int:pk>/', login_required(PollsterUpdateView.as_view()), name='pollster_update'),
    path('encuestador/estatus/<int:pk>/', login_required(PollsterStatusUpdateView.as_view()), name='pollster_status_update'),
]

usuario/forms.py
"""
Nombre del software: SIGETP

Descripción: Sistema Integrado de Información y Documentación Geoestadística y Tecnopolítica

Nombre del licenciante y año: Fundación CIDA (2017)

Autores: William Páez

La Fundación Centro Nacional de Desarrollo e Investigación en Tecnologías Libres (CENDITEL),
ente adscrito al Ministerio del Poder Popular para Educación Universitaria, Ciencia y Tecnología
(MPPEUCT), concede permiso para usar, copiar, modificar y distribuir libremente y sin fines
comerciales el "Software - Registro de bienes de CENDITEL", sin garantía
alguna, preservando el reconocimiento moral de los autores y manteniendo los mismos principios
para las obras derivadas, de conformidad con los términos y condiciones de la licencia de
software de la Fundación CENDITEL.

El software es una creación intelectual necesaria para el desarrollo económico y social
de la nación, por tanto, esta licencia tiene la pretensión de preservar la libertad de
este conocimiento para que contribuya a la consolidación de la soberanía nacional.

Cada vez que copie y distribuya el "Software - Registro de bienes de CENDITEL"
debe acompañarlo de una copia de la licencia. Para más información sobre los términos y condiciones
de la licencia visite la siguiente dirección electrónica:
http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/
"""
## @namespace usuario.forms
#
# Contiene las clases, atributos y métodos para los formularios a implementar en la aplicación usuario
# @author William Páez (wpaez at cenditel.gob.ve)
# @author <a href='http://www.cenditel.gob.ve'>Centro Nacional de Desarrollo e Investigación en Tecnologías Libres
# (CENDITEL) nodo Mérida - Venezuela</a>
# @author <a href='www.cida.gob.ve/'>Centro de Investigaciones de Astronomía "Francisco J. Duarte"</a>
# @copyright <a href='http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/'>Licencia de Software CENDITEL versión 1.2</a>
# @date 24-05-2017
# @version 1.0

from django import forms
from base.fields import IdentificationCardField, PhoneField
from django.utils.translation import ugettext_lazy as _
from .models import Profile, Communal
from django.contrib.auth.models import User
from django.core import validators
from base.models import State, Municipality, Parish, CommunalCouncil

class CommunalAdminForm(forms.ModelForm):
    """!
    Clase que contiene los campos del formulario del perfil usado en el panel administrativo

    @author William Páez (wpaez at cenditel.gob.ve)
    @copyright <a href='http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/'>Licencia de Software CENDITEL versión 1.2</a>
    @date 01-07-2018
    """

    ## Estado donde se ecnuetra ubicado el municipio
    state = forms.ModelChoiceField(
        label=_("Estado:"), queryset=State.objects.all(), empty_label=_("Seleccione..."),
        widget=forms.Select(attrs={
            'class': 'form-control select2', 'data-toggle': 'tooltip',
            'title': _("Seleccione el estado en donde se encuentra ubicada"),
        })
    )

    ## Municipio donde se encuentra ubicada la parroquia
    municipality = forms.ModelChoiceField(
        label=_("Municipio:"), queryset=Municipality.objects.all(), empty_label=_("Seleccione..."),
        widget=forms.Select(attrs={
            'class': 'form-control select2', 'data-toggle': 'tooltip', 'disabled': 'true',
            'title': _("Seleccione el municipio en donde se encuentra ubicada"),
        })
    )

    ## Parroquia donde se encuentra ubicado el consejo comunal
    parish = forms.ModelChoiceField(
        label=_("Parroquia:"), queryset=Parish.objects.all(), empty_label=_("Seleccione..."),
        widget=forms.Select(attrs={
            'class': 'form-control select2', 'data-toggle': 'tooltip', 'disabled': 'true',
            'title': _("Seleccione la parroquia en donde se encuentra ubicada"),
        })
    )

    class Meta:
        """!
        Meta clase del formulario que establece algunas propiedades

        @author William Páez (wpaez at cenditel.gob.ve)
        @copyright <a href='http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/'>Licencia de Software CENDITEL versión 1.2</a>
        @date 24-05-2017
        @version 1.0.0
        """

        model = User
        fields = '__all__'

class ProfileForm(forms.ModelForm):
    """!
    Clase que contiene los campos del formulario de perfil del usuario

    @author William Páez (wpaez at cenditel.gob.ve)
    @copyright <a href='http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/'>Licencia de Software CENDITEL versión 1.2</a>
    @date 25-06-2018
    """

    ## Username para identificar al usuario, en este caso se usa la cédula
    username = IdentificationCardField(
        validators=[
            validators.RegexValidator(
                r'^[VE][\d]{8}$',
                _("Introduzca un número de cédula válido. Solo se permiten números y una longitud de 8 carácteres. Se agregan ceros (0) si la longitud es de 7 o menos caracteres.")
            ),
        ]
    )

    ## Nombres del usuario
    first_name = forms.CharField(
        label=_("Nombres:"), max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control input-sm', 'data-toggle': 'tooltip',
                'title': _("Indique los Nombres"),
            }
        )
    )

    ## Apellidos del usuario
    last_name = forms.CharField(
        label=_("Apellidos:"), max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control input-sm', 'data-toggle': 'tooltip',
                'title': _("Indique los Apellidos"),
            }
        )
    )

    ## Correo del usuario
    email = forms.EmailField(
        label=_("Correo Electrónico:"), max_length=100,
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control input-sm email-mask', 'data-toggle': 'tooltip',
                'title': _("Indique el correo electrónico de contacto")
            }
        )
    )

    ## Teléfono del usuario
    phone = PhoneField(
        validators=[
            validators.RegexValidator(
                r'^\+\d{2}-\d{3}-\d{7}$',
                _("Número telefónico inválido. Solo se permiten números.")
            ),
        ]
    )

    ## Clave de acceso del usuario
    password = forms.CharField(
        label=_("Contraseña:"), max_length=128,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control input-sm', 'data-toggle': 'tooltip',
                'title': _("Indique una contraseña de aceso al sistema")
            }
        )
    )

    ## Confirmación de clave de acceso del usuario
    confirm_password = forms.CharField(
        label=_("Confirmar Contraseña:"), max_length=128,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control input-sm', 'data-toggle': 'tooltip',
                'title': _("Indique nuevamente la contraseña de aceso al sistema")
            }
        )
    )

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email):
            raise forms.ValidationError(_("El correo ya esta registrado"))
        return email

    def clean_confirm_password(self):
        confirm_password = self.cleaned_data['confirm_password']
        password = self.cleaned_data.get('password')
        if password != confirm_password:
            raise forms.ValidationError(_("La contraseña no es la misma"))

        return confirm_password

    class Meta:
        """!
        Meta clase del formulario que establece algunas propiedades

        @author William Páez (wpaez at cenditel.gob.ve)
        @copyright <a href='http://conocimientolibre.cenditel.gob.ve/licencia-de-software-v-1-3/'>Licencia de Software CENDITEL versión 1.2</a>
        @date 25-06-2018
        """

        model = User
        exclude = ['profile','level','date_joined']

class CommunalUpdateForm(ProfileForm):

    def __init__(self, *args, **kwargs):
        super(CommunalUpdateForm, self).__init__(*args, **kwargs)
        self.fields['password'].required = False
        self.fields['confirm_password'].required = False
        self.fields['password'].widget.attrs['disabled'] = True
        self.fields['confirm_password'].widget.attrs['disabled'] = True

    communal_council = forms.CharField(
        label=_("Consejo Comunal:"),
        max_length=500,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control input-sm', 'data-toggle': 'tooltip', 'readonly':'true',
                'title': _("Consejo Comunal que tiene asignado"),
            }
        ),required = False
    )

    def clean_email(self):
        email = self.cleaned_data['email']
        username = self.cleaned_data.get('username')
        if User.objects.filter(email=email).exclude(username=username):
            raise forms.ValidationError(_("El correo ya esta registrado "))
        return email

    def clean_confirm_password(self):
        pass

    class Meta:
        model = User
        exclude = [
            'profile','communal_council','password','date_joined','is_superuser',
            'is_staff','is_active','last_login'
        ]

class PollsterForm(ProfileForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(PollsterForm, self).__init__(*args, **kwargs)
        if Communal.objects.filter(profile=user.profile):
            communal = Communal.objects.get(profile=user.profile)
            self.fields['communal_council'].initial = communal.communal_council

    communal_council = forms.CharField(
        label=_("Consejo Comunal:"),
        max_length=500,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control input-sm', 'data-toggle': 'tooltip', 'readonly':'true',
                'title': _("Consejo Comunal que tiene asignado"),
            }

usuario/templates/usuario/login.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block content_header_title %}{% endblock %}
{% block contenido %}
    <h3 class="text-center">Portal de Acceso al Sistema</h3>
    <div class="login-box">
        <div class="login-box-body">
            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <p>
                        {{ error }}
                    </p>
                {% endfor %}
            {% endif %}
            <p class="login-box-msg">Inicia tu sesión</p>

            <form action="" method="post" autocomplete="off">
                {% csrf_token %}
                <div class="form-group has-feedback {% if form.username.errors %}has-error{% endif %}">
                    <input type="text" name="username" class="form-control sm-input" placeholder="usuario" data-toggle="tooltip" title="Indique el nombre de usuario" id="id_username"/>
                    <span class="glyphicon glyphicon-user form-control-feedback"></span>
                    {% include 'base/form.errors.html' with form_errors=form.username.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
                </div>
                <div class="form-group has-feedback {% if form.password.errors %}has-error{% endif %}">
                    <input type="password" name="password" class="form-control input-sm" placeholder="contraseña de acceso" data-toggle="tooltip" title="Indique la contraseña de acceso al sistema" />
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                    {% include 'base/form.errors.html' with form_errors=form.password.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
                </div>
                <div class="row">
                    <div class="col-xs-4">
                        <button type="submit" class="btn btn-primary btn-block btn-flat">Entrar</button>
                    </div>
                </div>
            </form>
            <br>
            <a href="{% url 'usuario:password_reset' %}">Yo olvidé mi contraseña</a><br>
            <a href="#" class="text-center">Registrar nuevo usuario</a>
        </div>
    </div>
<!-- /.login-box -->
{% endblock %}

usuario/templates/usuario/password_change_done.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block content_header_title %}Usuario{% endblock %}
{% block contenido %}
    <div class="box box-info">
        <div class="box-body">
            <p>{% trans 'Your password was changed.' %}</p>
        </div>
    </div>
{% endblock %}

usuario/templates/usuario/password_change_form.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block content_header_title %}Usuario{% endblock %}
{% block content_header_roadmap %}
    <li><a href="#">{% trans 'Usuario' %}</a></li>
    <li class="active">{% trans 'Cambiar Clave' %}</li>
{% endblock %}
{% block contenido %}
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Cambiar Contraseña</h3>
        </div>
        <div class="box-body">
            <form method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6 col-sm-6 col-xs-6">
                        <div class="form-group {% if form.old_password.errors %}has-error{% endif %}">
                            <label class="col-md-3 col-xs-3 col-sm-3 control-label" for="{{ form.old_password.auto_id }}">
                                {{ form.old_password.label_tag }}
                            </label>
                            <div class="col-md-9 col-xs-9 col-sm-9">
                                <div class="form-inline">
                                    {{ form.old_password }}
                                    <i class="ion ion-ios-medical item-requerido"></i>
                                </div>
                                {% include 'base/form.errors.html' with form_errors=form.old_password.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6 col-sm-6 col-xs-6">
                        <div class="form-group {% if form.new_password1.errors %}has-error{% endif %}">
                            <label class="col-md-3 col-xs-3 col-sm-3 control-label" for="{{ form.new_password1.auto_id }}">
                                {{ form.new_password1.label_tag }}
                            </label>
                            <div class="col-md-9 col-xs-9 col-sm-9">
                                <div class="form-inline">
                                    {{ form.new_password1 }}
                                    <i class="ion ion-ios-medical item-requerido"></i>
                                </div>
                                {% if form.new_password1.help_text %}
                                    {{ form.new_password1.help_text|safe }}
                                {% endif %}
                                {% include 'base/form.errors.html' with form_errors=form.new_password1.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-6">
                        <div class="form-group {% if form.new_password2.errors %}has-error{% endif %}">
                            <label class="col-md-3 col-xs-3 col-sm-3 control-label" for="{{ form.new_password2.auto_id }}">
                                {{ form.new_password2.label_tag }}
                            </label>
                            <div class="col-md-9 col-xs-9 col-sm-9">
                                <div class="form-inline">
                                    {{ form.new_password2 }}
                                    <i class="ion ion-ios-medical item-requerido"></i>
                                </div>
                                {% if form.new_password2.help_text %}
                                    {{ form.new_password2.help_text|safe }}
                                {% endif %}
                                {% include 'base/form.errors.html' with form_errors=form.new_password2.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="box-footer text-right">
                    <button type="submit" class="btn btn-primary btn-sm" data-toggle="tooltip" >{% trans 'Enviar' %}</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

usuario/templates/usuario/password_reset_complete.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block content_header_title %}Usuario{% endblock %}
{% block contenido %}
    <div class="box box-info">
        <div class="box-body">
	        <h3 class="text-center">Su contraseña se reestableció correctamente</h3>

	        <p class="text-center"><a  href="{% url 'usuario:login' %}">Iniciar Sesión</a></p>
        </div>
    </div>
{% endblock %}

usuario/templates/usuario/password_reset_confirm.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block content_header_title %}Usuario{% endblock %}
{% block contenido %}
    <div class="box box-info">
        {% if validlink %}
            <div class="box-header with-border">
                <h3 class="box-title">Nueva Contraseña</h3>
            </div>
            <div class="box-body">
                <form method="post">
                    {% csrf_token %}

                    {{ form.new_password1.errors }}
                    <label for="id_new_password1">Nueva contraseña:</label>
                    {{ form.new_password1 }}

                    {{ form.new_password2.errors }}
                    <label for="id_new_password2">Confirme contraseña:</label>{{ form.new_password2 }}
                    <div class="box-footer text-right">
                        <button type="submit" class="btn btn-primary btn-sm" data-toggle="tooltip">{% trans 'Enviar' %}</button>
                    </div>
                </form>
            </div>
        {% else %}
            <div class="box-header with-border">
                <h3 class="box-title">Enlace Inválido</h3>
            </div>
            <div class="box-body">
                <p class="text-center">ESTE ENLACE YA HA SIDO UTILIZADO</p>
            </div>
        {% endif %}
    </div>
{% endblock %}

usuario/templates/usuario/password_reset_done.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block content_header_title %}Usuario{% endblock %}
{% block contenido %}
    <div class="box box-info">
        <div class="box-body">
            <h4>Te hemos enviado un correo con un enlace para reestablecer tu contraseña</h4>
        </div>
    </div>
{% endblock %}

usuario/templates/usuario/password_reset_email.html
Solicitaste reestablecimiento de contraseña.
Click en el siguiente link para crear una nueva contraseña.
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'usuario:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
Tu nombre de usuario es: {{ user.get_username }}

usuario/templates/usuario/password_reset_form.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block content_header_title %}Usuario{% endblock %}
{% block contenido %}
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Recuperar Contraseña</h3>
        </div>
        <div class="box-body">
            <form method="post">
	            {% csrf_token %}
	            <label for="id_email">Correo:</label> {{ form.email }}
                <div class="box-footer text-right">
                    <button type="submit" class="btn btn-primary btn-sm" data-toggle="tooltip">{% trans 'Enviar' %}</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

usuario/templates/usuario/pollster.list.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block content_header_title %}{% trans 'Usuario' %}{% endblock %}
{% block content_header_roadmap %}
    <li><a href="#">{% trans 'Usuario' %}</a></li>
    <li class="active">{% trans 'Encuestador' %}</li>
{% endblock %}
{% block contenido %}
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Encuestador - Listar</h3><br>
        </div>

        <div class="box-header">
            <a href="{% url 'usuario:pollster_create' %}" class="btn btn-success pull-left">Registrar</a>
        </div>

        <div class="box-body">
            <div class="row box-body table-responsive">
                <!--<div class="col-md-12 col-sm-12 col-xs-12">-->
                    <table class="table table-striped table-hover table-bordered display dataTable blue-table" id="table" style="width:100%">
                        <thead>
                            <tr>
                                <th>Usuario</th>
                                <th>Nombres</th>
                                <th>Apellidos</th>
                                <th>Correo</th>
                                <th>Teléfono</th>
                                <th>Activo</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for pollster in object_list %}
                            <tr>
                                <td> {{ pollster.profile.user.username }} </td>
                                <td> {{ pollster.profile.user.first_name }} </td>
                                <td> {{ pollster.profile.user.last_name }} </td>
                                <td> {{ pollster.profile.user.email }} </td>
                                <td> {{ pollster.profile.phone }} </td>
                                {% if pollster.profile.user.is_active %}
                                    <td> Si <a href="{% url 'usuario:pollster_status_update' pollster.profile.user.id %}" data-toggle="tooltip" title="Cambiar Estatus"><i class="fa fa-pencil"></i></a> </td>
                                {% else %}
                                    <td> No <a href="{% url 'usuario:pollster_status_update' pollster.profile.user.id %}" data-toggle="tooltip" title="Cambiar Estatus"><i class="fa fa-pencil"></i></a> </td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                <!--</div>-->
            </div>
        </div>
    </div>
{% endblock %}
{% block extra_footer %}
    <script type="text/javascript">
        $(document).ready(function() {
            var table = $('#table').DataTable();

            button_datatable(table);
        });
    </script>
{% endblock %}

usuario/templates/usuario/pollster.status.update.html
{% extends 'base/base.html' %}
{% load i18n %}
{% block content_header_title %}{% trans 'Usuario' %}{% endblock %}
{% block content_header_roadmap %}
    <li>{% trans 'Usuario' %}</li>
    <li>{% trans 'Encuestador' %}</li>
    <li class="active">{% trans 'Estatus del Usuario' %}</li>
{% endblock %}
{% block contenido %}
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Estatus del Usuario</h3>
        </div>
        <div class="box-body">
            <form method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6 col-sm-6 col-xs-6">
                        <div class="form-group {% if form.is_active.errors %}has-error{% endif %}">
                            <label class="col-md-3 col-xs-3 col-sm-3 control-label" for="{{ form.is_active.auto_id }}">
                                {{ form.is_active.label }}
                            </label>
                            <div class="col-md-9 col-xs-9 col-sm-9">
                                <div class="form-inline">{{ form.is_active }}</div>
                                {% include 'base/form.errors.html' with form_errors=form.is_active.errors col_title_error='col-sm-2' col_msg_error='col-sm-10' %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box-footer text-right">
                    <a href="{% url 'usuario:pollster_list' %}" class="btn btn-primary btn-sm">Atrás</a>
                    <button type="reset" class="btn btn-primary btn-sm" data-toggle="tooltip">{% trans 'Limpiar' %}</button>
                    <button type="submit" class="btn btn-primary btn-sm" data-toggle="tooltip">{% trans 'Actualizar' %}</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}